name: Checks
on: [push]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
            ${{ runner.os }}-
      - name: Lint
        run: |
          yarn
          yarn compas lint
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
            ${{ runner.os }}-
      - name: Build
        run: |
          yarn
          yarn build
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]
    runs-on: ${{ matrix.os }}
    needs:
      - build
      - lint
    if: github.ref == 'refs/heads/main'
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
            ${{ runner.os }}-
      - name: Build
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          yarn
          yarn build
          yarn export
          cp ./CNAME ./out/CNAME
          cp ./.nojekyll ./out/.nojekyll
          git add ./out
          git commit -m "chore: publish docs for $COMMIT_SHA"
          git subtree push --prefix out origin gh-pages
