name: CI / push
on: [push]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Lint
        run: |
          yarn
          yarn compas lint

  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    needs:
      - lint
    if: github.ref == 'refs/heads/main'
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Copy to out
        # We keep running Yarn here, as we may want to add some preprocessing
        run: |
          yarn
          yarn compas build

      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "chore: publish docs for {sha}\n\n{msg}"
