name: Checks
on: [push]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
            ${{ runner.os }}-
      - name: Lint
        run: |
          yarn
          yarn format
          yarn checks:run
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
            ${{ runner.os }}-
      - name: Build
        run: |
          yarn
          yarn build
